---
title: "TODO"
author: "Jesse Mostipak"
date: "10/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Things to do
* select multiple years and create a stacked bar chart
* does "minty" apply to a gt or reactable table?
* move each plot to its own navpage?
* change the color based on a threshold value
* progressive brushing (see Mastering Shiny)
* fix up the labels, make it pretty(er)
* fuss with the layout (friable)

## DONE
* Dig in to bslib and thematic
* line graph showing trends over time
  + ability to select based on type
* Play with plotly
* Explore ggiraph
* add hover to bar chart
* add a slider to the year that then updates a graph and data table with the calculated average value
  + ability to see change over time, like next//previous
  + animate changes over time
* add a data table
* hovering and interactivity with plots

## WON'T DO
* scatterplot that updates with reactiveVal() based on brush selection
  + use scatterplot to fill a data table
  + LOLJK we only have one numeric column :/